updated

diff --git a/.github/actions/db-apply-migrations/action.yaml b/.github/actions/db-apply-migrations/action.yaml
--- a/.github/actions/db-apply-migrations/action.yaml
+++ b/.github/actions/db-apply-migrations/action.yaml
@@ -20,6 +20,8 @@ inputs:
   cicd-sql:
     description: "Path to cicd/sql directory"
     required: true
+  runner-download-migrations:
+    description: "migration script generated in previous job will be downloaded in this runner machines directory"
 
 runs:
   using: "composite"
@@ -27,7 +29,7 @@ runs:
     - uses: actions/download-artifact@v4
       with:
         name: db-migration-scripts
-        path: sql-migration-scripts/
+        path: ${{ inputs.runner-download-migrations }}
 
     - name: Check DB connectivity before applying migration
       shell: bash
@@ -48,7 +50,7 @@ runs:
         echo "📂 Workspace files:"
         ls -lrta ${{ github.workspace }}
         echo "📄 Checking migration.sql:"
-        file ${{ github.workspace }}/sql-migration-scripts/migration.sql || echo "migration.sql not found"
+        file ${{ github.workspace }}/${{ inputs.runner-download-migrations }}/migration.sql || echo "migration.sql not found"
 
     - name: Debug Docker inputs
       shell: bash
@@ -58,7 +60,7 @@ runs:
         echo "SQL_DB=${{ inputs.sql-db }}"
         echo "SQL_USER=${{ inputs.sql-user }}"
         echo "SQL_PASS=${{ inputs.sql-pass }}"
-        ls -l ${{ github.workspace }}/sql-migration-scripts/migration.sql
+        ls -l ${{ github.workspace }}/${{ inputs.runner-download-migrations }}/migration.sql
 
     - name: Run SQL Applier to apply migration
       shell: bash
@@ -68,5 +70,5 @@ runs:
           -e DB_NAME=${{ inputs.sql-db }} \
           -e DB_USER=${{ inputs.sql-user }} \
           -e DB_PASS="${{ inputs.sql-pass }}" \
-          -v ${{ github.workspace }}/sql-migration-scripts/migration.sql:/app/migration.sql \
+          -v ${{ github.workspace }}/${{ inputs.runner-download-migrations }}/migration.sql:/app/migration.sql \
           sql-applier
